config/routes.rb
Trackit::Application.routes.draw do
  get "main/index"
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :activity_groups

  resources :activities do
    resources :time_trackers
    resources :tasks
  end

  root to: 'main#index'
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :activity
  
  validates :description, presence: true
  validates :description, length: {minimum: 2, maximum: 95}
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def new
    @task = Task.new
  end
  
  def create
    @activity = current_user.activities.find(params[:activity_id])
    
    unless task = @activity.add_task!(params[:task])
      flash[:error] = I18n.t "errors.task.generic"
      # render or redirect_to
      return
    end
    @task = task
    
    respond_to do |format|
      format.html { redirect_to activity_path(activity) }
      format.js
    end
  end
  
  def update
    activity = current_user.activities.find(params[:activity_id])
    @task = activity.tasks.find(params[:id])
    activity.update_task!(params[:id])
    respond_to do |format|
      format.html { redirect_to activity_path(activity) }
      format.js
    end
  end
  
  def destroy
    activity = current_user.activities.find(params[:activity_id])
    @task = activity.tasks.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html {redirect_to activity_path(activity)}
      format.js
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
%h3 
	Tasks
%span.form-inline.centered
	= form_for [@activity, @task], remote: true do |f|
		= f.text_field :description, {placeholder: 'Enter task description and click + to create a new task', class: 'input-task'}
		= f.submit "+", class: 'btn btn-danger'

app/views/tasks/_task.html.haml
= form_for [task.activity, task], remote: true do |f|
	= f.check_box :complete, class: 'pull-left'
	= f.submit 'Update'
	= f.label :complete, task.description, class: 'pull-left'
	= link_to "(remove)", activity_task_path(task.activity, task), method: :delete, data: { confirm: 'Are you sure?'}, remote: true

app/views/tasks/create.js.erb
$('#incomplete-tasks').prepend("<%= j render partial: 'task', locals: {task: @task} %>");
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/new.html.haml
Anythign

app/views/tasks/update.js.erb
<% if @task.complete? %>
	$('#edit_task_<%= @task.id %>').prependTo('#incomplete-tasks');
<% else %>
	$('#edit_task_<%= @task.id %>').prependTo('#complete-tasks');
<% end %>