config/routes.rb
Trackit::Application.routes.draw do
  get "main/index"
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :activity_groups

  resources :activities do
    resources :time_trackers
    resources :tasks
  end

  root to: 'main#index'
  

end

app/models/activity_group.rb
class ActivityGroup < ActiveRecord::Base
  attr_accessible :title
  
  has_many :activity_groups
  belongs_to :activity_group
  has_many :activities, dependent: :destroy
  
  validates :title, presence: true

  def self.all_base
    all.select {|activity_group| activity_group if activity_group.activity_group_id.nil?}
  end
end

app/controllers/activity_groups_controller.rb
class ActivityGroupsController < ApplicationController
  load_and_authorize_resource except: [:create, :update]

  helper_method :activity_groups
  def index
    @activity_groups = current_user.activity_groups.all_base
    @activities_base = current_user.activities.all_base
    @activity_group = current_user.activity_groups.new
    @activity = current_user.activities.new
    @activities = current_user.activities.all
  end

  def show
    @activity_group = current_user.activity_groups.find(params[:id])
    @activities = @activity_group.activities.all
  end

  def new
    @activity_group = ActivityGroup.new
  end
  
  def create
    activity_group_id = params[:activity_group].delete(:activity_group_id)
    @activity_group = current_user.activity_groups.new(params[:activity_group]) 
    if !activity_group_id.empty?
      @activity_group.activity_group_id = current_user.activity_groups.find(activity_group_id).id
    else
      @activity_group.activity_group_id = nil
    end
    authorize! :create, @activity_group
    if @activity_group.save
      flash[:notice] = I18n.t "notices.activity_group.created"
      redirect_to activity_groups_path
    else 
      flash[:error] = "#{@activity_group.errors.messages}"
      render 'new'
    end
  end

  def edit
    @activity_group = current_user.activity_groups.find(params[:id])
  end
  
  def update
    activity_group_id = params[:activity_group].delete(:activity_group_id)
    @activity_group = current_user.activity_groups.find(params[:id])
    if !activity_group_id.empty?
      @activity_group.activity_group_id = current_user.activity_groups.find(activity_group_id).id
    else 
      @activity_group.activity_group_id = nil
    end
    authorize! :update, @activity_group
    if @activity_group.update_attributes(params[:activity_group])
      flash[:notice] = I18n.t "notices.activity_group.updated"
    else
      flash[:error] = "#{activity_group.errors.messages}"
    end
    redirect_to activity_groups_path
  end
  
  def destroy
    current_user.activity_groups.find(params[:id]).destroy
    flash[:notice] = I18n.t "notices.activity_group.destroyed"
    redirect_to activity_groups_path
  end

  private

  def activity_groups
    @activity_groups ||= current_user.activity_groups.all
  end
end

app/helpers/activity_groups_helper.rb
module ActivityGroupsHelper
end

app/views/activity_groups/_activity_group.html.haml
%ul.span6
	%li.span1
		%i.icon-folder-close.folder
	%li.span2
		= link_to activity_group.title, activity_group_path(activity_group)
		
	- if !activity_group.activity_groups.empty?
		- activity_group.activity_groups.each do |activity_group|
			= render partial: 'activity_group', locals: {activity_group: activity_group}
			
	- if !activity_group.activities.empty?
		- activity_group.activities.each do |activity|
			= render partial: 'activities/activity', locals: {activity: activity}
			

app/views/activity_groups/_edit.html.haml
.modal-header
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  %h2 Edit Activity Group
= render partial: 'form', locals: {btn_text: 'Update Activity Group'}

app/views/activity_groups/_form.html.haml
=form_for @activity_group do |f|
  .modal-body
    %div
      =f.label :title
      =f.text_field :title
    %div
      =f.label :activity_group_id
      =f.select :activity_group_id, options_from_collection_for_select(activity_groups, "id", "title"), {:include_blank => 'None'}
  .modal-footer
    =f.submit btn_text, class: 'btn btn-primary'

app/views/activity_groups/_new.html.haml
.modal-header
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  %h2 New Activity Group
= render partial: 'form', locals: {btn_text: 'Add Activity Group'}

app/views/activity_groups/_tasks.html.haml
.span6
  %h2 Tasks
  .well  
    %h3.label.label-important Incomplete Tasks
    - if @activities.present?
      - @activities.each do |activity|
        %h4= activity.title
        #incomplete-tasks= render partial: activity.incomplete_tasks
    - else
      %h4 No tasks need to be completed at this time.
  .well  
    %h3.label.label-success Complete Tasks
    - if @activities.present?
      - @activities.each do |activity|
        %h4= activity.title
        #complete-tasks= render partial: activity.complete_tasks
    - else
      %h4 You have no completed tasks.

app/views/activity_groups/edit.html.haml
= render partial: 'form', locals: {btn_text: 'Update Activity Group'}

app/views/activity_groups/index.html.haml
.row
  .span6
    %h1.padding_bottom1 Activity Groups

    - if !@activity_groups.empty? or !@activities_base.empty?
      %ul.span6
        %li.span1
          %i.icon-globe
        %li.span2 Name
          
      = render @activity_groups
      = render @activities_base
    - else
      %h2.extra_padding You have no Activity Groups yet. Add one and start managing your time. 
    
    =link_to "Create Activity Group", new_activity_group_path, {class: 'btn', remote: true, id: 'create_activity_group'}
    =link_to "Create Activity", new_activity_path, {class: 'btn', remote: true, id: 'create_activity'}

  = render partial: 'tasks'

  .span12
    #new_activity_group.modal.hide.fade= render partial: 'activity_groups/new'
    #new_activity.modal.hide.fade= render partial: 'activities/new'

app/views/activity_groups/new.html.haml
= render partial: 'form', locals: {btn_text: 'Add Activity Group'}

app/views/activity_groups/show.html.haml
.row
  .span6
    %h2= @activity_group.title

    - if @activities.present?
      %ul.span6
        %li.span1
          %i.icon-globe
        %li.span2 Name

    = render @activities
    
    = link_to "Edit", edit_activity_group_path(@activity_group), id: 'edit_activity_group', remote: true
    |
    = link_to "Delete", activity_group_path(@activity_group), {confirm: (I18n.t "confirmations.activity_group.delete"), method: :delete}
    |
    = link_to "Back", activity_groups_path
 
  .span6= render partial: 'tasks'

#update_activity_group.modal.hide.fade= render partial: 'edit'