config/routes.rb
Trackit::Application.routes.draw do
  get "main/index"
  
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :activity_groups

  resources :activities do
    resources :time_trackers
    resources :tasks
  end

  root to: 'main#index'
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :title, :description
  
  belongs_to :user
  belongs_to :activity_groups
  has_many :time_trackers, order: :id, dependent: :destroy
  has_many :tasks, dependent: :destroy
  
  
  validates :title, :description, presence: true
  validates :title, length: {minimum: 2, maximum: 40}
  validates :description, length: {minimum: 6, maximum: 500}
  
  def self.all_base
    all.select {|activity| activity if activity.activity_group_id.nil?}
  end
  
  def clock_in
    time_tracker = time_trackers.create! clock_in: Time.zone.now
  end
  
  def clock_out
    last_time_tracker = time_trackers.last
    if last_time_tracker[:clock_in].to_date == Time.zone.now.to_date
      last_time_tracker.update_attribute :clock_out, Time.zone.now
    else
      last_time_tracker.update_attribute :clock_out, last_time_tracker[:clock_in].end_of_day
      add_days
    end
  end
  
  def clocked_in?
    last_time_tracker = time_trackers.last
    return false if last_time_tracker.blank?
    last_time_tracker.clock_in and not last_time_tracker.clock_out
  end
  
  def clocked_out?
    last_time_tracker = time_trackers.last
    return false if last_time_tracker.nil?
    true if last_time_tracker.clock_out
  end
  
  def add_task!(task)
    tasks.create! description: task[:description], complete: false
    rescue ActiveRecord::RecordInvalid
    return false
  end
  
  def update_task!(task)
    task = tasks.find(task)
    if task.complete == false
      task.update_attribute :complete, true
    else
      task.update_attribute :complete, false
    end
    rescue ActiveRecord::RecordNotFound
    return false
  end
  
  def incomplete_tasks
    tasks.select {|task| task.complete == false}.reverse
  end
  
  def complete_tasks
    tasks.select {|task| task.complete == true}.reverse
  end
  
  private
  
  def add_days
    array =  (((time_trackers.last.clock_in + 1.day).to_date)..(Date.today - 1.day)).to_a
    day2 = Date.today - 1.day
    array.each do |time|
      time = time.to_time
      time_trackers.create! clock_in: time, clock_out: time.end_of_day
    end
    time_trackers.create! clock_in: Time.zone.now.beginning_of_day, clock_out: Time.zone.now
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  helper_method :graph
  helper_method :activity_groups
  
  load_and_authorize_resource except: [:create, :update]
  
  def show
    @activity = current_user.activities.find(params[:id])
    @task = Task.new
    @incomplete_tasks = @activity.incomplete_tasks
    @complete_tasks = @activity.complete_tasks
    
    @params = params
    if graph.valid?
      graph.time_frame
    else
      flash.now[:error] = "#{graph.errors.messages.first.second[0]}"
      graph.default
    end
  end
  
  def new
    @activity = Activity.new
  end
  
  def create
    activity_group_id = params[:activity].delete(:activity_group_id)
    @activity = current_user.activities.new(params[:activity])  
    if !activity_group_id.empty?
      @activity.activity_group_id = current_user.activity_groups.find(activity_group_id).id
    else
      @activity.activity_group_id = nil
    end

    authorize! :create, @activity
    if @activity.save
      flash[:notice]= I18n.t "notices.activity.created"
      redirect_to activity_path(@activity)
    else
      flash[:error]= "#{@activity.errors.messages}"
      render 'new'
    end
  end
  
  def edit
    @activity = current_user.activities.find(params[:id])
  end
  
  def update
    activity_group_id = params[:activity].delete(:activity_group_id)
    @activity = current_user.activities.find(params[:id])
    
    if !activity_group_id.empty?
      @activity.activity_group_id = current_user.activity_groups.find(activity_group_id).id
    else
      @activity.activity_group_id = nil
    end
          
    authorize! :update, @activity
    
    if @activity.update_attributes(params[:activity])
      flash[:notice]= I18n.t "notices.activity.updated"
      redirect_to activity_path(@activity)
    else
      flash[:error]= "#{@activity.errors.messages}"
      render 'new'
    end
  end
  
  def destroy
    current_user.activities.find(params[:id]).destroy
    flash[:notice] = I18n.t "notices.activity.destroyed"
    redirect_to activity_groups_path
  end
  
  private 
  
  def graph
      @graph ||= Graph.new(@activity, @params)
  end

  def activity_groups
    @activity_groups ||= current_user.activity_groups.all
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.haml
%ul.span6
	%li.span1
		%i.icon-file
	%li.span2
		.text=link_to activity.title, activity_path(activity)

app/views/activities/_clock.html.haml
.clock
	#Date
	%ul.unstyled
		%li#hours.pull-left
		%li#point.pull-left :
		%li#min.pull-left
		%li#point.pull-left :
		%li#sec.pull-left

app/views/activities/_edit.html.haml
.modal-header
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  %h2 Edit Activity
=render partial: 'form', locals: {activity: @activity, btn_text: 'Update activity'}

app/views/activities/_form.html.haml
= form_for activity do |f|
  .modal-body
    %div
      =f.label :title
      =f.text_field :title
    %div
      =f.label :description
      =f.text_area :description
    %div
      =f.label :activity_group_id
      =f.select :activity_group_id, options_from_collection_for_select(activity_groups, "id", "title"), {:include_blank => 'None'}
  
  .modal-footer
    =f.submit btn_text,{class: 'btn btn-large btn-primary'}

app/views/activities/_graph.html.haml
= content_tag :div, "", id: "activity_graph", data: {name: graph.name, minutes: graph.minutes, year: graph.year, month: graph.month, day: graph.day, data_hash: graph.data_hash}

app/views/activities/_graph.js.erb
// $('li').click (function () {
// 	$(this).hide();
// });
// // "<%= render partial: 'graph', locals: {graph: graph} %>"

app/views/activities/_new.html.haml
.modal-header
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  %h2 Create Activity
=render partial: 'activities/form', locals: {activity: @activity, btn_text: 'Create Activity'}

app/views/activities/edit.html.haml
=render partial: 'form', locals: {activity: @activity, btn_text: 'Update activity'}

app/views/activities/new.html.haml
=render partial: 'form', locals: {activity: @activity, btn_text: 'Create Activity'}

app/views/activities/show.html.haml
.row
  .span12
    .pull-left.padding-bottom0
      = link_to 'Back', activity_groups_path
      |
      = link_to 'Edit', edit_activity_path, id: 'edit_activity', remote: true
    #update_activity.modal.hide.fade= render partial: 'edit'

  .span2.well
    %p= render partial: 'clock'
    %br
    - if @activity.clocked_out?

      %h2=@activity.title
      %p=@activity.description
      %h4="Clocked out at #{@activity.time_trackers.last.clock_out.strftime("%H:%M")}"
      %p=link_to "Clock in", activity_time_trackers_path(@activity), {class: 'btn btn-large btn-primary', method: :post}

    - elsif @activity.clocked_in?

      %h2=@activity.title
      %p=@activity.description
      %h4="Clocked in at #{@activity.time_trackers.last.clock_in.strftime("%H:%M")} #{@activity.time_trackers.last.clock_in.to_date.strftime("(%m/%d)")}"
      %p=link_to "Clock out", activity_time_tracker_path(@activity), {class: 'btn btn-large btn-primary', method: :put}

    - else

      %h2=@activity.title
      %p=@activity.description
      %p There are no time trackers at the current time. Planning on working on this activity? Start tracking by Clocking in!
      %p=link_to "Clock in", activity_time_trackers_path(@activity), {class: 'btn btn-large btn-primary', method: :post}
		
    %br
      %p Total time
      %h4= graph.total_time
			

  .span9
    = render partial: 'graph', locals: {graph: graph}

    .graph_date_selector.well
      %span.pull-left
        = link_to "Last 7 days", activity_path(@activity, days: 7), {class: 'pull-left btn'}
        = link_to "Last 14 days", activity_path(@activity, days: 14), {class: 'pull-left btn'}
        = link_to "Last 30 days", activity_path(@activity, days: 30), {class: 'pull-left btn'}
      %span.pull-right
        = form_tag activity_path(@activity), method: :get do
          = text_field_tag :start_time, nil , {placeholder: 'Start Date', class: 'pull-left input-small'}
          = text_field_tag :end_time, nil , {placeholder: 'End Date', class: 'pull-left input-small'}
          = submit_tag 'Show custom dates', class: 'btn'
		
    #new-tasks= render partial: 'tasks/form'
    #existing-tasks
      .well	
        %h4.label.label-important Incomplete Tasks
        #incomplete-tasks= render @incomplete_tasks
      .well	
        %h4.label.label-success Complete Tasks
        #complete-tasks= render @complete_tasks